### ISSUE TITLE
Bottom border for headers

### ISSUE THREAD

**Issue by marcinkunert** [davidmyersdev/ink-mde#76]
First of all thanks for this awesome editor. This is already the 3rd I'm trying out, best so far.

I've tried to add bottom borders to the h1 and h2 elements inside the editor:

![image](https://github.com/davidmyersdev/ink-mde/assets/2963232/df339c49-5f20-4f3c-b873-297559ceb1a3)

So I've checked, they have 

```html
<div class="cm-line"><span class="ͼ14 ͼ1i">#</span><span class="ͼ14"> Header 1</span></div>
<div class="cm-line"><span class="ͼ15 ͼ1i">##</span><span class="ͼ15"> Header 2</span></div>
<div class="cm-line"><span class="ͼ16 ͼ1i">###</span><span class="ͼ16"> Header 3</span></div>
```

So there is the css I've come up with:
```css
.cm-line:has(.ͼ14), .cm-line:has(.ͼ15) {
  padding-bottom: .3em;
  border-bottom: 1px solid #eaecef;
}
```

Afterward I've noticed that after deploying the code the class name changed:

```html
<div class="cm-line"><span class="ͼl ͼy">##</span><span class="ͼl"> Header 1</span></div>
```
 
Is there a way to add the bottom borders?
